# Generated by Django 2.2.1 on 2019-06-17 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Task'},
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='admin',
        ),
        migrations.AddField(
            model_name='tasks',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.CharField(default='No name', max_length=32),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.CreateModel(
            name='TasksUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.Tasks')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='associated', through='todo_list.TasksUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
