# Generated by Django 2.2.1 on 2019-06-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20190617_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.PositiveIntegerField(blank=True, choices=[(3, 'Baixa'), (5, 'Normal'), (8, 'Alta')]),
        ),
    ]
