# Generated by Django 2.2.1 on 2019-06-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20190619_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.PositiveIntegerField(choices=[(3, 'Baixa'), (5, 'Normal'), (8, 'Alta')]),
        ),
        migrations.AlterField(
            model_name='tasksusers',
            name='status',
            field=models.BooleanField(choices=[(0, 'Pendente'), (1, 'Concluído')], default=False),
        ),
    ]
