# Generated by Django 2.2.1 on 2019-06-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20190621_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksusers',
            name='status',
            field=models.BooleanField(choices=[(0, 'Pendente'), (1, 'Fazendo'), (2, 'Concluído')], default=False),
        ),
    ]
