# Generated by Django 2.2.1 on 2019-06-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20190626_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksusers',
            name='status',
            field=models.BooleanField(choices=[(0, 'Pendente'), (1, 'Concluído')], default=False),
        ),
    ]
